version: "3.7"
services:
    led:
        container_name: led-api
        build: .
        image: led-boot:latest
        environment:
            - JAVA_OPTIONS=-Xmx384m -Xms256
            - SERVER_PORT=8080
        ports: 
            - 8080:8080
        links:
            - redis
    redis:
        container_name: redis
        image: redis:latest
        command: redis-server --requirepass ${REDIS_PASS}
        port:
            - 6379:6379
