version: "3.7"
services:
    app:
        container_name: led-api
        build: .
        image: led-boot:latest
        environment:
            - JAVA_OPTIONS=-Xmx384m -Xms256
            - SERVER_PORT=8080
        ports: 
            - 8080:8080
